### ISSUE TITLE
Haluan nähdä palapelin kuvan

### ISSUE THREAD

**Issue by jenraii** [HeliKyllinen/Selainpeli#24]
Ensimmäinen käyttäjätarina Sprint 2:selle.

**Comment by HeliKyllinen** [comment]
Luotiin index.html ja MainController.java tiedostot. Lisättiin pom.xml puuttuva thymeleaf dependency. Ensin käytettiin kovakoodattua kuvaa ja kun se saatiin näkyviin, niin vaihdettiin tilalle kuvan URL.
