### ISSUE TITLE
Haluan pystyä kokoamaan palapelin

### ISSUE THREAD

**Issue by jenraii** [HeliKyllinen/Selainpeli#27]
Neljäs käyttäjätarina Sprint 2:selle. Palapelin kokoamista käsittelevät koodin osat sisältävät hiiren tapahtumien käsittelyn (onMouseDown, onMouseMove, onMouseUp) ja tarkistuksen palapelin valmistumisen osalta (checkIfPuzzleCompleted). Nämä toiminnot mahdollistavat pelaajan vuorovaikutuksen pelin kanssa, jolloin palat voidaan siirtää ja järjestää oikein.

**Comment by sakariarasola** [comment]
Commit bc50471 joitain funktioita muutettu ja lisätty myös uusia
