### ISSUE TITLE
Palojen liikuttamisen ongelman ratkaisu

### ISSUE THREAD

**Issue by HeliKyllinen** [HeliKyllinen/Selainpeli#38]
Palat häviävät tällä hetkellä ilmeisesti toistensa alle, tämä pitää estää sekä palat menevät itsestään oikeille paikoille kun vain klikkaa palaa, joka on selkeästi väärässä paikassa.

**Comment by sakariarasola** [comment]
Commit bc50471 ongelmaa on vähän ratkaistu, palat eivät enää mene paikoilleen klikkaamalla, lisäksi palat voivat nyt olla 'ruudukon' ulkopuolella mutta liikkuvat vieläkin jäykästi ja menevät toistensa päälle välillä.

**Comment by sakariarasola** [comment]
Commit 4f95656 palapeliä on helompi pelata nyt, kun ruudukko on näkyvillä, niin palat menevät helpommin paikoilleen ja jäävät alle Z-indexin avulla, jotta ei tule hämmennystä mihin muut palat katoavat. Lisäksi paloja luotaessa kuva ei enää sahaudu oikealta puolelta pois. Ainoa uusi ongelma näiden muutosten myötä on se, että palat eivät mene enää ollenkaan ruudukon ulkopuolelle (palat voivat jäädä palapeliruudukon reunojen alle). Paras veikkaus on se, että moni funktio index.html:ssä on riippuvainen (puzzle)containerista, niin se rikkoo jotenkin randomX ja randomY logiikan. Vähän on kokeiltu eri fixejä, mutta parhaimmassa tapauksessa palat menee taas ulkopuolelle mutta tämä muutos rikkoo kokonaan palapelin.

**Comment by HeliKyllinen** [comment]
Ei jatkettu palojen vientiä containerin ulkopuolelle ajan loppuessa kesken. Toimii kuitenkin niin, että pelin saa kasattua.
