### ISSUE TITLE
Rahti alustus

### ISSUE THREAD

**Issue by HeliKyllinen** [HeliKyllinen/Selainpeli#41]
Dockerfilen + .yml-tiedoston luonti, application.properties Rahtia varten. Servicen ja Routen luonti Rahdissa. Build config myös aloitettu mutta build ei käynnisty vielä vaikka webhook on lisätty GitHubiin.

**Comment by sakariarasola** [comment]
Build ei käynnisty jostain syystä, ainoa mahdollinen vihje saattaa olla, että mariadb podin lokissa tulee jatkuvasti ''access denied'' virheviestejä.
